version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: >
            sh -c "sleep 5 && php artisan key:generate && php artisan migrate --seed && php-fpm"
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:latest
        container_name: laravel_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "mysql"
            MYSQL_DATABASE: tlu_management
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis:latest
        container_name: laravel_redis
        restart: always
        ports:
            - "6379:6379"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: laravel_phpmyadmin
        restart: always
        environment:
            PMA_HOST: laravel_mysql
            PMA_USER: root
            PMA_PASSWORD: mysql
        ports:
            - "8080:80"
        depends_on:
            - mysql
volumes:
    mysql_data:
